export const REQUEST_LABS = 'REQUEST_LABS';
export const RECEIVE_LABS = 'RECEIVE_LABS';

export const REQUEST_BLOGS = 'REQUEST_BLOGS';
export const RECEIVE_BLOGS = 'RECEIVE_BLOGS';

export const REQUEST_BLOGTAGS = 'REQUEST_BLOGTAGS';
export const RECEIVE_BLOGTAGS = 'RECEIVE_BLOGTAGS';