export const REQUEST_LABS = 'REQUEST_LABS';
export const RECEIVE_LABS = 'RECEIVE_LABS';

export const REQUEST_BLOGS = 'REQUEST_BLOGS';
export const RECEIVE_BLOGS = 'RECEIVE_BLOGS';

export const REQUEST_BLOGTAGS = 'REQUEST_BLOGTAGS';
export const RECEIVE_BLOGTAGS = 'RECEIVE_BLOGTAGS';

export const REQUEST_BLOGARTICLE = 'REQUEST_BLOGARTICLE';
export const RECEIVE_BLOGARTICLE = 'RECEIVE_BLOGARTICLE';

export const REQUEST_FRIENDS = 'REQUEST_FRIENDS';
export const RECEIVE_FRIENDS = 'RECEIVE_FRIENDS';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';